In [1]:
import torch
from torch import nn # nn contains all of PyTorch's building blocks for neural networks
import matplotlib.pyplot as plt

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [12]:
class RandomNN(nn.Module):
    def __init__(self):
        super().__init__()
        self.layer = nn.Linear(in_features=1, out_features=1)
        #self.layer_2 = nn.Linear(in_features=10, out_features=10)
        #self.layer_3 = nn.Linear(in_features=10, out_features=1)
        self.relu = nn.ReLU() # <- add in ReLU activation function
        # Can also put sigmoid in the model 
        # This would mean you don't need to use it on the predictions
        # self.sigmoid = nn.Sigmoid()

    def forward(self, x):
      # Intersperse the ReLU activation function between layers
       #return self.layer_3(self.relu(self.layer_2(self.relu(self.layer_1(x)))))
       return self.layer(x)

NN_model = RandomNN().to(device)
print(NN_model)

RandomNN(
  (layer): Linear(in_features=1, out_features=1, bias=True)
  (relu): ReLU()
)


In [68]:
NN_model.layer.weight, NN_model.layer.bias

(Parameter containing:
 tensor([[2.]], device='cuda:0', requires_grad=True),
 Parameter containing:
 tensor([0.9712], device='cuda:0', requires_grad=True))

In [67]:
NN_model.layer.weight

Parameter containing:
tensor([[2.]], device='cuda:0', requires_grad=True)

In [50]:
x = torch.tensor([[0.0], [1.0]]).to(device)
print(x)

tensor([[0.],
        [1.]], device='cuda:0')


In [52]:
res = NN_model(x)
print(res)

tensor([[0.9712],
        [0.6088]], device='cuda:0', grad_fn=<AddmmBackward0>)


In [66]:
NN_model.layer.weight[0,0]

tensor(2., device='cuda:0', grad_fn=<SelectBackward0>)

In [65]:
with torch.no_grad():
    NN_model.layer.weight[0,0] = 2
    

https://stackoverflow.com/questions/66724071/manually-assign-weights-using-pytorch
https://www.reddit.com/r/pytorch/comments/m9azt9/manually_assign_weights_using_pytorch/
these links might help!